server.port=8081
spring.main.allow-bean-definition-overriding=true
# Playwright browsers will be downloaded on first run if necessary (may require network)

# Actuator / Micrometer
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=scraper-api-rama-mini

# Configuración de Resilience4j para Scraper
resilience4j.retry.instances.scraperService.maxAttempts=3
resilience4j.retry.instances.scraperService.waitDuration=2s
resilience4j.retry.instances.scraperService.enableExponentialBackoff=true
resilience4j.retry.instances.scraperService.exponentialBackoffMultiplier=2

resilience4j.circuitbreaker.instances.scraperService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.scraperService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.scraperService.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.scraperService.permittedNumberOfCallsInHalfOpenState=3
# Ver consultas SQL ejecutadas por Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Ver detalles de peticiones web y Spring MVC
logging.level.org.springframework.web=DEBUG

# Ver logs específicos de tu proyecto (reemplaza por tu paquete real)
logging.level.com.redprocesal=DEBUG
# Configuración de Retry (Reintentos)

app.api.key=34809238490283409284028340923840
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
server.error.include-stacktrace=always
